version: "3"

services:
  redis: 
    image: redis
    container_name: redis
    networks:
      - cache
    ports:
      - "6379:6379"
    volumes:
      - redis:/var/lib/redis/data
  
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    networks:
      - cache
    depends_on:
      - redis
    ports:
      - "8001:8001"
    volumes:
      - redisinsight:/db


networks:
  cache:

volumes:
  redisinsight:
  redis: